apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # base64 for "postgres"
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # base64 for "password"
  POSTGRES_DB: bXlkYg==  # base64 for "mydb"